const test = require('node:test');
const assert = require('node:assert/strict');
const FinanceUtils = require('../business-tracker-frontend/js/finance-utils.js');
const ExchangeRateService = require('../business-tracker-frontend/js/exchange-rate.js');

test('legacy and unsupported currencies normalize to LKR', () => {
    assert.equal(FinanceUtils.normalizeCurrency(), 'LKR');
    assert.equal(FinanceUtils.normalizeCurrency('usd'), 'USD');
    assert.equal(FinanceUtils.normalizeCurrency('EUR'), 'LKR');
});

test('converts between USD and LKR without changing same-currency amounts', () => {
    assert.equal(FinanceUtils.convertAmount(2, 'USD', 'LKR', 300), 600);
    assert.equal(FinanceUtils.convertAmount(600, 'LKR', 'USD', 300), 2);
    assert.equal(FinanceUtils.convertAmount(15, 'USD', 'USD', 0), 15);
    assert.throws(() => FinanceUtils.convertAmount(10, 'USD', 'LKR', 0));
});

test('unavailable conversions never fabricate a differently labelled amount', () => {
    assert.equal(FinanceUtils.convertAmountOrUnavailable(15, 'USD', 'USD', null), 15);
    assert.equal(Number.isNaN(FinanceUtils.convertAmountOrUnavailable(15, 'USD', 'LKR', null)), true);
    assert.equal(FinanceUtils.formatMoney(Number.NaN, 'LKR'), 'LKR —');
    assert.equal(FinanceUtils.formatAmountNumber(Number.NaN, 'USD'), '—');
});

test('normalizes income sources without hiding historical sources', () => {
    assert.equal(FinanceUtils.normalizeIncomeSource('Room Revenue - Booking'), 'Room Revenue');
    assert.equal(FinanceUtils.normalizeIncomeSource('Restaurant'), 'Restaurant');
    assert.equal(FinanceUtils.normalizeIncomeSource('Bar'), 'Other');
    assert.equal(FinanceUtils.normalizeIncomeSource('Spa'), 'Other');
});

test('calculates restaurant totals from valid line items', () => {
    assert.equal(FinanceUtils.calculateRestaurantTotal([
        { quantity: 2, unitPrice: 10 },
        { quantity: 3, unitPrice: 5 }
    ]), 35);
});

test('restaurant paid orders create a deterministic income model', () => {
    const order = {
        hotelId: 'hotel-1',
        date: '2026-07-27',
        orderNumber: 'ORD-1',
        totalAmount: 25,
        currency: 'usd',
        paymentStatus: 'paid',
        createdBy: 'Manager'
    };
    assert.equal(FinanceUtils.restaurantIncomeDocumentId('abc'), 'restaurant_abc');
    assert.deepEqual(FinanceUtils.buildRestaurantIncome('abc', order), {
        hotelId: 'hotel-1',
        date: '2026-07-27',
        source: 'Restaurant',
        amount: 25,
        currency: 'USD',
        restaurantOrderId: 'abc',
        isAutoGenerated: true,
        description: 'Restaurant order ORD-1',
        createdBy: 'Manager'
    });
    assert.equal(FinanceUtils.buildRestaurantIncome('abc', { ...order, paymentStatus: 'pending' }), null);
});

test('booking income is deterministic and carries every finance dimension', () => {
    const booking = {
        hotelId: 'hotel-1', guestName: 'Guest', roomNumber: '101', checkIn: '2026-07-27',
        checkOut: '2026-07-28', guestCount: 2, mealPackage: 'Full Board', totalAmount: 125,
        currency: 'usd', bookingChannel: 'Agoda', paymentStatus: 'paid', status: 'upcoming'
    };
    assert.equal(FinanceUtils.bookingIncomeDocumentId('booking-1'), 'booking_booking-1');
    const income = FinanceUtils.buildBookingIncome('booking-1', booking);
    assert.equal(income.amount, 125);
    assert.equal(income.currency, 'USD');
    assert.equal(income.bookingChannel, 'Agoda');
    assert.equal(income.bookingId, 'booking-1');
    assert.equal(income.source, 'Room Revenue - Booking');
    assert.equal(income.isAutoGenerated, true);
    assert.equal(FinanceUtils.buildBookingIncome('booking-1', { ...booking, paymentStatus: 'pending' }), null);
});

test('HTML escaping protects stored finance text', () => {
    assert.equal(
        FinanceUtils.escapeHtml(`<img src=x onerror="bad()"> O'Reilly & Co.`),
        '&lt;img src=x onerror=&quot;bad()&quot;&gt; O&#39;Reilly &amp; Co.'
    );
});

test('rate freshness uses a 24-hour cache window', () => {
    const now = Date.parse('2026-07-27T12:00:00Z');
    assert.equal(FinanceUtils.isRateFresh(now - 23 * 60 * 60 * 1000, now), true);
    assert.equal(FinanceUtils.isRateFresh(now - 25 * 60 * 60 * 1000, now), false);
});

test('validates provider payloads', () => {
    assert.equal(ExchangeRateService.validatePayload({ result: 'success', rates: { LKR: 300 } }), 300);
    assert.throws(() => ExchangeRateService.validatePayload({ result: 'error' }));
});

function mockFirestore(cachedData) {
    const writes = [];
    return {
        writes,
        collection() {
            return {
                doc() {
                    return {
                        async get() {
                            return { exists: Boolean(cachedData), data: () => cachedData };
                        },
                        async set(data) { writes.push(data); }
                    };
                }
            };
        }
    };
}

test('uses a fresh Firestore rate without calling the provider', async () => {
    const now = Date.parse('2026-07-27T12:00:00Z');
    const db = mockFirestore({ rate: 300, fetchedAt: new Date(now - 1000), source: 'cache' });
    let fetchCalled = false;
    const result = await ExchangeRateService.loadUsdToLkrRate(db, {
        now,
        fetchImpl: async () => { fetchCalled = true; throw new Error('should not run'); }
    });
    assert.equal(result.rate, 300);
    assert.equal(result.fromCache, true);
    assert.equal(result.stale, false);
    assert.equal(fetchCalled, false);
});

test('refreshes stale rates and writes the validated provider value', async () => {
    const now = Date.parse('2026-07-27T12:00:00Z');
    const db = mockFirestore({ rate: 290, fetchedAt: new Date(now - 30 * 60 * 60 * 1000) });
    const result = await ExchangeRateService.loadUsdToLkrRate(db, {
        now,
        fetchImpl: async () => ({
            ok: true,
            json: async () => ({ result: 'success', rates: { LKR: 305 }, time_last_update_unix: now / 1000 })
        })
    });
    assert.equal(result.rate, 305);
    assert.equal(result.fromCache, false);
    assert.equal(db.writes.length, 1);
    assert.equal(db.writes[0].rate, 305);
});

test('falls back to a stale cached rate when the provider fails', async () => {
    const now = Date.parse('2026-07-27T12:00:00Z');
    const db = mockFirestore({ rate: 290, fetchedAt: new Date(now - 30 * 60 * 60 * 1000) });
    const result = await ExchangeRateService.loadUsdToLkrRate(db, {
        now,
        fetchImpl: async () => { throw new Error('offline'); }
    });
    assert.equal(result.rate, 290);
    assert.equal(result.stale, true);
    assert.equal(result.error, 'offline');
});
