(function (root, factory) {
    const api = factory();
    if (typeof module === 'object' && module.exports) module.exports = api;
    if (root) root.FinanceUtils = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
    const SUPPORTED_CURRENCIES = ['LKR', 'USD'];

    function normalizeCurrency(currency) {
        const normalized = String(currency || 'LKR').trim().toUpperCase();
        return SUPPORTED_CURRENCIES.includes(normalized) ? normalized : 'LKR';
    }

    function requireValidRate(rate) {
        const numericRate = Number(rate);
        if (!Number.isFinite(numericRate) || numericRate <= 0) {
            throw new Error('A valid USD to LKR exchange rate is required.');
        }
        return numericRate;
    }

    function convertAmount(amount, fromCurrency, toCurrency, usdToLkrRate) {
        const numericAmount = Number(amount || 0);
        if (!Number.isFinite(numericAmount)) return 0;

        const from = normalizeCurrency(fromCurrency);
        const to = normalizeCurrency(toCurrency);
        if (from === to) return numericAmount;

        const rate = requireValidRate(usdToLkrRate);
        return from === 'USD' ? numericAmount * rate : numericAmount / rate;
    }

    function convertAmountOrUnavailable(amount, fromCurrency, toCurrency, usdToLkrRate) {
        const numericAmount = Number(amount || 0);
        if (!Number.isFinite(numericAmount)) return Number.NaN;
        const from = normalizeCurrency(fromCurrency);
        const to = normalizeCurrency(toCurrency);
        if (from === to) return numericAmount;
        try {
            return convertAmount(numericAmount, from, to, usdToLkrRate);
        } catch (error) {
            return Number.NaN;
        }
    }

    function formatMoney(amount, currency, options) {
        const normalized = normalizeCurrency(currency);
        const numericAmount = amount == null || amount === '' ? 0 : Number(amount);
        if (!Number.isFinite(numericAmount)) return `${normalized} —`;
        const maximumFractionDigits = options && Number.isInteger(options.maximumFractionDigits)
            ? options.maximumFractionDigits
            : normalized === 'USD' ? 2 : 0;

        return `${normalized} ${numericAmount.toLocaleString(undefined, {
            minimumFractionDigits: normalized === 'USD' ? 2 : 0,
            maximumFractionDigits
        })}`;
    }

    function formatAmountNumber(amount, currency) {
        const numericAmount = Number(amount);
        if (!Number.isFinite(numericAmount)) return '—';
        return numericAmount.toFixed(normalizeCurrency(currency) === 'USD' ? 2 : 0);
    }

    function normalizeIncomeSource(source) {
        const value = String(source || '').trim();
        if (value.includes('Room Revenue')) return 'Room Revenue';
        if (value === 'Restaurant') return 'Restaurant';
        return 'Other';
    }

    function matchesOriginalCurrency(record, selectedCurrency) {
        if (!selectedCurrency || selectedCurrency === 'all') return true;
        return normalizeCurrency(record && record.currency) === normalizeCurrency(selectedCurrency);
    }

    function calculateRestaurantTotal(items) {
        if (!Array.isArray(items)) return 0;
        return items.reduce((total, item) => {
            const quantity = Number(item && item.quantity);
            const unitPrice = Number(item && item.unitPrice);
            if (!Number.isFinite(quantity) || !Number.isFinite(unitPrice)) return total;
            return total + (quantity * unitPrice);
        }, 0);
    }

    function restaurantIncomeDocumentId(orderId) {
        if (!orderId || String(orderId).includes('/')) {
            throw new Error('A valid restaurant order ID is required.');
        }
        return `restaurant_${orderId}`;
    }

    function bookingIncomeDocumentId(bookingId) {
        if (!bookingId || String(bookingId).includes('/')) {
            throw new Error('A valid booking ID is required.');
        }
        return `booking_${bookingId}`;
    }

    function buildRestaurantIncome(orderId, order) {
        if (!order || order.paymentStatus !== 'paid') return null;
        return {
            hotelId: order.hotelId,
            date: order.date,
            source: 'Restaurant',
            amount: Number(order.totalAmount || 0),
            currency: normalizeCurrency(order.currency),
            restaurantOrderId: orderId,
            isAutoGenerated: true,
            description: `Restaurant order ${order.orderNumber || orderId}`,
            createdBy: order.createdBy || 'Unknown'
        };
    }

    function buildBookingIncome(bookingId, booking) {
        if (!booking || booking.paymentStatus !== 'paid') return null;
        const mealLabel = booking.mealPackage || 'No Package';
        return {
            hotelId: booking.hotelId,
            date: booking.checkIn || booking.date,
            source: 'Room Revenue - Booking',
            amount: Number(booking.totalAmount || 0),
            currency: normalizeCurrency(booking.currency),
            bookingChannel: booking.bookingChannel || '',
            bookingId,
            isAutoGenerated: true,
            description: `Booking: ${booking.guestName || 'Guest'} | Room ${booking.roomNumber || 'N/A'} | ${booking.checkIn || ''} to ${booking.checkOut || ''} | ${Number(booking.guestCount || 1)} guests | ${mealLabel} | PAID${booking.status === 'checked_out_early' ? ' | EARLY CHECK-OUT' : ''}`
        };
    }

    function escapeHtml(value) {
        return String(value == null ? '' : value).replace(/[&<>'"]/g, character => ({
            '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;'
        })[character]);
    }

    function timestampToMillis(value) {
        if (!value) return 0;
        if (typeof value.toMillis === 'function') return value.toMillis();
        if (typeof value.toDate === 'function') return value.toDate().getTime();
        if (value instanceof Date) return value.getTime();
        if (typeof value === 'number') return value;
        const parsed = new Date(value).getTime();
        return Number.isFinite(parsed) ? parsed : 0;
    }

    function isRateFresh(timestamp, now, maxAgeMs) {
        const timestampMs = timestampToMillis(timestamp);
        const nowMs = timestampToMillis(now || Date.now());
        const ageLimit = Number(maxAgeMs || 24 * 60 * 60 * 1000);
        return timestampMs > 0 && nowMs >= timestampMs && (nowMs - timestampMs) < ageLimit;
    }

    return {
        SUPPORTED_CURRENCIES,
        normalizeCurrency,
        convertAmount,
        convertAmountOrUnavailable,
        formatMoney,
        formatAmountNumber,
        normalizeIncomeSource,
        matchesOriginalCurrency,
        calculateRestaurantTotal,
        restaurantIncomeDocumentId,
        bookingIncomeDocumentId,
        buildRestaurantIncome,
        buildBookingIncome,
        escapeHtml,
        timestampToMillis,
        isRateFresh
    };
});
